FROM golang:1.8.3 as builder
RUN mkdir -p /go/src/github.com/gianksp/websrv
WORKDIR /go/src/github.com/gianksp/websrv

COPY . .

RUN go get ./... \
    && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM scratch as web-server
COPY --from=0 /go/src/github.com/gianksp/websrv/main .
CMD ["/main"]
